### ISSUE TITLE
Demo is doing a 505 

### ISSUE THREAD

**Issue by Ducasse** [DuneSt/MaterialDesignLite#102]
http://eph-b922e2d9.swarm.pharocloud.com/MDLComponentsDemoApplication

**Comment by jecisc** [comment]
I should deploy a demo directly on my server one day :(

**Comment by jecisc** [comment]
@Ducasse I begun to deploy it here: https://mdl.ferlicot.fr

I'll change the README when i'll be sure it's stable.
