### ISSUE TITLE
Need version 1.2.0 from current master

### ISSUE THREAD

**Issue by SabineMa** [DuneSt/MaterialDesignLite#103]
Hi Cyril,

we are in the last strokes for going online with our application. Til now I used the master branch of MDL (`github://DuneSt/MaterialDesignLite:master/src`). But I don't want to put production versions into the productive environment but only versions.

I tried with ` 'github://DuneSt/MaterialDesignLite:v1.0.2/src`' but there is the MDLAnchorButton missing (at least).

So my question: could you create a v1.0.3 from the current master for me?

Regards 
Sabine

**Comment by jecisc** [comment]
Hi! I'll try to take a look tomorrow or next week if it's fine with you.

**Comment by jecisc** [comment]
Hum... I see that the current stable is the version 1.1.0 and not 1.0.2, so if I release a version it will be a 1.1.1 or 1.2.0 depending if new features where added or not. I did not check the history but it will probably be 1.2.0.

**Comment by jecisc** [comment]
Is that ok with you @SabineMa?

**Comment by SabineMa** [comment]
It seems that I need new glasses:-) I did not see the v1.1.0!
I can use v1.1.0, I will close this issue!
Sorry for the noise, Cyril

**Comment by jecisc** [comment]
I'll probably release a 1.2.0 soon because I started to look at the sync with the github repo :)

**Comment by jecisc** [comment]
Also, just for info, I try to get a tag on every commit of the master branch that does not concern the README or a text file like this. Even for bugfix I increment the patch number. So, if you can depend on master, you can also depend on a release.
