### ISSUE TITLE
MDLDialog>>openButtonId: missing .close eventListener

### ISSUE THREAD

**Issue by SabineMa** [DuneSt/MaterialDesignLite#11]
currently, in openButtonId:, there is missing the following statement:

```
dialog.querySelector(''.close'').addEventListener(''click'', function() \{
      dialog.close();
    });
```

Without this, it is not possible to close the dialog, except with clicking at the backdrop.
But if the user clicks on "ok" and some action is done, the programmer should have the possibility to close the dialog. Adding the following line allows this by adding the class .close to the button.

It is documented here in the examples:
https://getmdl.io/components/index.html#dialog-section

so, please change it from:

```
openButtonId: id
   self id ifNil: [ self id: id, '-dialog' ].
    self script: (JSStream on: 
        ('(function() \{
         var dialog = document.querySelector(''#{1}'');
       var showDialogButton = document.querySelector(''#{2}'');
       if (! dialog.showModal) \{
         dialogPolyfill.registerDialog(dialog);
       }
       showDialogButton.addEventListener(''click'', function() \{
         dialog.showModal();
            document.querySelector(''.backdrop'').addEventListener(''click'', function() \{
                dialog.close();
            });
            document.querySelector(''._dialog_overlay'').style.display = "none";
       });
        })()' format: {self id.  id}))
```

to: 

```
openButtonId: id
   self id ifNil: [ self id: id, '-dialog' ].
    self script: (JSStream on: 
        ('(function() \{
         var dialog = document.querySelector(''#{1}'');
       var showDialogButton = document.querySelector(''#{2}'');
       if (! dialog.showModal) \{
         dialogPolyfill.registerDialog(dialog);
       }
       showDialogButton.addEventListener(''click'', function() \{
         dialog.showModal();
            document.querySelector(''.backdrop'').addEventListener(''click'', function() \{
                dialog.close();
            });
    "This is the new statement"     
        dialog.querySelector(''.close'').addEventListener(''click'', function() \{
        dialog.close();
    });
"end of new statement"

            document.querySelector(''._dialog_overlay'').style.display = "none";
       });
        })()' format: {self id.  id}))
```

**Comment by jecisc** [comment]
Done in: f15220a935eb42d01b40806c1614fdc52b661bcd

**Comment by jecisc** [comment]
This break the dialogs. I reverted the fix and I will investigate later.

**Comment by SabineMa** [comment]
Hi Cyril,

sorry, I forgot to tell you that this only works if the button has the class "close".
Can you please check if you can add it like this?

>   "This is the new statement"  
> if ($(''.close'').length>0) \{
>       dialog.querySelector(''.close'').addEventListener(''click'', function() \{
>         dialog.close();
>     });
> }   
> "end of new statement"

So, if you want to close the dialog after clicking on one of its buttons, you have to add the class "close" to it. Otherwise it stays open.
regards
Sabine

**Comment by Valtena** [comment]
Hi, I had split the js to add it in MDLlibrary.

For your problem I have put this : 
`closeElems= dialog.querySelectorAll(".close");
       for(i=0;i<closeElems.length;i++){
          closeElems[i].addEventListener("click", function() {
            dialog.close();
          });
       }`

It's only push on smalltalkhub for now. Wait after Jecisc to push on git.

**Comment by jecisc** [comment]
I finished to port the changes about dialog. It should be fine now. Can you test the development version and check it is fine for you Sabine?

Thank you for your patience, sorry for the time it took, too much work.

**Comment by SabineMa** [comment]
Hi Cyril,
I tested the development version and it is fine. Thank you for your work!
Sabine

2017-01-06 21:38 GMT+01:00 CyrilFerlicot <notifications@github.com>:

**Comment by jecisc** [comment]
Cool!So  I close this issue.
Thank you for the feedback!

**Comment by SabineMa** [comment]
Thanks. Are you planning to release a new master with this in the next
weeks?

2017-01-08 16:07 GMT+01:00 CyrilFerlicot <notifications@github.com>:

**Comment by jecisc** [comment]
It's possible that some students work a little on MDL (3rd year of university probably working on their first real project).
I will probably release a 1.2.0 after that. 
I also want to update the MDL version we use to the 1.3.0. But I will need to test all our widgets with it before releasing.

**Comment by SabineMa** [comment]
Would be great.
I am just upgrading my app to the mdl 1.3.0
If there are problems, I will tell you.

2017-01-08 16:12 GMT+01:00 CyrilFerlicot <notifications@github.com>:
