### ISSUE TITLE
#detectIndex: is part of Morphic.

### ISSUE THREAD

**Issue by pdebruic** [DuneSt/MaterialDesignLite#184]
https://github.com/DuneSt/MaterialDesignLite/blob/f3eda5e69e539ffcad80e905b114d50a88a37c5e/src/Material-Design-Lite-Widgets.package/MDLNestedList.class/instance/elementsDisplayList.st#L10

Is there something else tht would work here?

**Comment by jecisc** [comment]
I'll take a look tomorrow.

**Comment by jecisc** [comment]
This is weird, I do not see it in Morphic but in Collection-Abstract.

**Comment by jecisc** [comment]
![2018-06-04_02-03-06](https://user-images.githubusercontent.com/9519971/41069595-f7b7c0b6-69ee-11e8-89ee-d27bce7baa74.png)

**Comment by jecisc** [comment]
![pharo_2018-06-07_01-05-41](https://user-images.githubusercontent.com/9519971/41069602-0251f884-69ef-11e8-9ded-ee67c0028257.png)

**Comment by jecisc** [comment]
Apparently, it changed in Pharo 7. Now it is not part of Morphic anymore.

Does that raise a problem for the Gemstone compatibility?

**Comment by pdebruic** [comment]
No I just have to add it to the list of extensions but I don't understand what using it gives you vs #indexOf: except that you don't have to test for `=0`

**Comment by jecisc** [comment]
@pdebruic #indexOf: takes an element. #detectIndex: takes a block.
