### ISSUE TITLE
Add Gemstone compatibility

### ISSUE THREAD

**Issue by jecisc** [DuneSt/MaterialDesignLite#189]
There was already some work to add Gemstone compatibility to MDL.

We should push it and add Gemstone to TravisCI.

**Comment by gcotelli** [comment]
Are you using the semantic versioning support in metacello (some
dependencies are using 'v1.?') ? As far as I know this needs to use the GH
API to traverse the tags but it's doing it without authentication. I was
tired of getting the API rate limit message, so stopped using this support,
and I just created a vMAJOR tag that's moved to match the last released
version for this MAJOR one. For example you can have versions v1.0.0 v1.1.0
(this are fixed commits) and v1 (matching the V1.10 commit). If later we
release v1.2.0, remove the v1 tag and create it again but pointing to
v1.2.0 commit. For dependencies we tend to use the vMAJOR tag (in case
you're doing semantic versioning). It's a bit manual job, but I never see
again the rate limit message failing in the builds.

**Comment by jecisc** [comment]
@gcotelli I use semantic versioning but with a hack for the API limit rate.

What I do when I release a version is that I create three tags. For example for the v1.2.0 of MaterialColors:
- v1.2.0
- v1.2.x
- v1.x.x

In this case, v1.x.x already existed on the same commit than the v1.1.0, so I just moved the tag to the commit of v1.2.0. 

Pro of this system:
- It does not rely on Github API

Cons:
- I need to move the tags myself.

**Comment by jecisc** [comment]
The problem with gemstone seems to come from the way it downloads a zip of the project to load it.

**Comment by jecisc** [comment]
For the missing methods problem I just found this project:

https://github.com/glassdb/PharoCompatibility/tree/master/repository

Maybe it can help to add it as a dependency of the Gemstone package.

**Comment by jecisc** [comment]
Merged into development in 622dbdbaf55476826baf84aebbc85eb07f4ae2cd
