### ISSUE TITLE
`MDColor` has a lowercase class variable

### ISSUE THREAD

**Issue by krono** [DuneSt/MaterialDesignLite#22]
`MDColor` uses `colors` as a class variable.

In Squeak the compiler complains because it wants to help distinguish class variables (capitalized) from class instance variables (lowercase)

Could colors either be a class instance variable or be capitalized?

**Comment by jecisc** [comment]
I agree. 
In Pharo this is not impossible to use lowercase for class variables but the convention is to use uppercase too.
I will capitalize it.

**Comment by krono** [comment]
Quickfix is making it a class-inst var (see #23)
