### ISSUE TITLE
New Widget: Expension panel and Accordions

### ISSUE THREAD

**Issue by jecisc** [DuneSt/MaterialDesignLite#236]
https://material.angular.io/components/expansion/examples

**Comment by juliendelplanque** [comment]
I have a prototype of Expansion.
Will implement accordions as well and propose it.

Preview:

<img width="1440" alt="Capture d’écran 2019-10-13 à 21 27 03" src="https://user-images.githubusercontent.com/8260456/66720694-862cbb80-ee00-11e9-8c4b-4ed42cdc5b03.png">
<img width="1437" alt="Capture d’écran 2019-10-13 à 21 26 54" src="https://user-images.githubusercontent.com/8260456/66720695-875de880-ee00-11e9-8fda-d5801ac83aef.png">

**Comment by juliendelplanque** [comment]
Expansion panel have been implemented and integrated in PR #264 .

I will create a new issue for accordions.
