### ISSUE TITLE
Tooltip of NestedList is not usable

### ISSUE THREAD

**Issue by jecisc** [DuneSt/MaterialDesignLite#31]
For now the list use a transform3D and this messup with the tooltip. We should remove this. 
Also the tooltips charged dynamically are not usable.

**Comment by jecisc** [comment]
There is a temporary solution commited by Yann on the Smalltalkhub repo but this is a little a hack so before moving it to github I would like to clean it.

**Comment by Valtena** [comment]
The real problem is that tooptip created in ajax  haven't position  bind by  MDL. When this problem will resolve, we can remove transformation and absolute position

**Comment by jecisc** [comment]
The bug about dynamic tooltip might be caused by the fact that we do not use ajax with JQuery binding but we do it "by hand" instead. By changing this we might correct the bug.

**Comment by jecisc** [comment]
Done in: 5ef2a0800fce14ee4433c91e870d5e8c578919f4
