### ISSUE TITLE
Link as buttons

### ISSUE THREAD

**Issue by jecisc** [DuneSt/MaterialDesignLite#38]
If we want to change of page we need a link. But in some case we want the link to have the look of a button. For now we can wrap a button inside an anchor. But this is not valid HTML5. 

We should have MDLAnchors  with the same API than the buttons to customize them.

**Comment by pdebruic** [comment]
I have some code for this.  I add the MDLAnchorButton class that is instantiated witf #mdlAnchorButton

I'll put up a PR

**Comment by jecisc** [comment]
Hi! 
Thank you! 
I was thinking of using trait to manage this. MDLTButtonLikeTag that would be used by MDLButton and MDLAnchor to avoid duplication. What do you think about that?

**Comment by pdebruic** [comment]
I don't like Traits.  Primarily because I've never spent the time to learn why/when they're better than subclassing and composition.  So I admit its a personal failing ;)


Are there other uses of Traits in the package now?

**Comment by pdebruic** [comment]
And really I'm fine with Traits, but I intend to port this to GemStone, and they flatten traits (I think), so would prefer to not use them if possible, so that the codebases are as similar as possible

**Comment by jecisc** [comment]
For now, no.

Here trait can be cool because we will make two brush share the same api.

To know if we should inherit or compose someone told me: if what you want to use is the same objet be more specified, you should inherit. If you add a behavior that is not related to the kind of object you should compose. 

Here and anchor is not a specialization of a button. So it should not inherit it. :)

If you don't want to lose time you can do a PR with your changes and I can factorize the code with a trait later. :)

**Comment by pdebruic** [comment]
How do you feel about me doing a MDLButtonLikeTag with MDLButtonTag and MDLAnchorTag subclasses ?

Excludes traits and duplication ;)

**Comment by pdebruic** [comment]
oh wait.  that won't work

**Comment by jecisc** [comment]
Oh yes, I forgot the portability since I never used Gemstone or Squeak. 
Yes I would like to be compatible with them while it is not too much work to do.

**Comment by jecisc** [comment]
I think the only way will be to duplicate since we need to inherit from WAAnchor and WAButton.

**Comment by jecisc** [comment]
Merge in: https://github.com/DuneSt/MaterialDesignLite/pull/40
