### ISSUE TITLE
why do chips always attempt to set the 'mdl-chip--contact' css Class?

### ISSUE THREAD

**Issue by pdebruic** [DuneSt/MaterialDesignLite#66]
e.g. in the MDLChipTag>>#with: method with this:

```
canvas document
		addLoadScript:
			(canvas jQuery ajax
				script: [ :s | s << (((canvas jQuery id: self id) children: '.mdl-chip__contact') parent addClass: #'mdl-chip--contact') ])
```

It makes an extra round trip to the server for seemingly no reason.  I think you shouldn't do it at all ever but if you have to you should at least change it to:

```
with: aBlock
	self id.	"Do mot remove me. I am here to make sure that the id is set before the chip is rendered."
       self script:(((canvas jQuery id: self id) children: '.mdl-chip__contact') parent addClass: #'mdl-chip--contact').
	super with: aBlock.
```

**Comment by jecisc** [comment]
At the beginning there was no chips in MDL so I did our own chips. Then MDL guys did the component and it was hard to keep the same API in seaside with their component. This is why I use a script to add the class when the chip is a contact chip. 

At the time I did this I was not really into Javascipt and the JQuery binding of Seaside. When I'll get some time I'll check this issue. (probably mid-April if it can wait that long for you).

**Comment by jecisc** [comment]
I think the same could be done in

    addDeleteWithAppendBlock: aBlock
	    self class: #'mdl-chip__deletable'.
	    self ensureId.
	    canvas document addLoadScript: (canvas jQuery ajax script: [ :s | s << (canvas jQuery id: self id) append: aBlock ])

**Comment by jecisc** [comment]
In fact I took the time to do it now :) 

Done in: b366ddd80d513c7b7c9f1a0de56e66e240f3533e

**Comment by pdebruic** [comment]
Hahahaha.  Nice work.   All these items I can work around.  I just report the issue to github so it gets considered/cleaned eventually. 

What I'm saying is don't rush to fix things on my account.  If it ever happens that I can't fix it for myself I'll let you know explicitly.

**Comment by jecisc** [comment]
Ok :)
I'll probably release a v1.1.0 today with all the fix that should not break the API.
