### ISSUE TITLE
MDLButton>> initialize, please remove type="button" 

### ISSUE THREAD

**Issue by SabineMa** [DuneSt/MaterialDesignLite#9]
in MDLButton>> initialize there is now 

`self resetType.`

I ask for removing that line.
 
Reason: it adds 
`type="button" `and that causes callback not to work.

Example:

```
renderContentOn: html
	html form
		attributeAt: 'target' put: '_top';
		with: [ html mdlButton
				rippleEffect;
				id: #saveButtonID;
				callback: [ 'callback' inspect ];
				onClick: (html jQuery ajax script: [ :s | 'onClick' inspect ]) , html jQuery ajax serializeThis;
				with: 'Test' ]
```

with the resetType -> onClick works but not callback
without the resetType -> onClick works, also callback

Those who need resetType button can add it themselves but I don't have possibility to remove it easily

Or is there something wrong with my example?

**Comment by jecisc** [comment]
I do not know the influence of the type. Maybe Kévin or Thomas can help about that when they will come back from holidays.

**Comment by jecisc** [comment]
I talked with Thomas and he said he changed it to not trigger the forms when they use ajax. 

So the right way to do it would be to remove that and to add a method as "beAjaxButton" or "beButtonType" or "buttonType"

**Comment by jecisc** [comment]
Done in: d8f000bb1adc1048641a6213d74a9bf8064fa64c

There was already a #bePush in the superclass.

@SabineMa is it fine for you?
